version: '3.8'

services:
  delete-account-ms:
    build:
      context: ./delete-account-ms
      image: alexismendozaa/delete-account-ms:latest  
    ports:
      - "3008:5008"
    networks:
      - user_service_network

  edit-avatar-ms:
  
    build:
      context: ./edit-avatar-ms
      image: alexismendozaa/edit-avatar-ms:latest  
    ports:
      - "3007:5007"
    networks:
      - user_service_network

  edit-email-ms:
    build:
      context: ./edit-email-ms
      image: alexismendozaa/edit-email-ms:latest  
    ports:
      - "3005:5005"
    networks:
      - user_service_network

  edit-password-ms:
    build:
      context: ./edit-password-ms
      image: alexismendozaa/edit-password-ms:latest  
    ports:
      - "3006:5006"
    networks:
      - user_service_network

  edit-username-ms:
    build:
      context: ./edit-username-ms
      image: alexismendozaa/edit-username-ms:latest  
    ports:
      - "3004:5004"
    networks:
      - user_service_network

  get-info-ms:
    build:
      context: ./get-info-ms
      image: alexismendozaa/get-info-ms:latest  
    ports:
      - "3009:5009"
    networks:
      - user_service_network

networks:
  user_service_network:
    driver: bridge
