<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.examples.com/wsdl/UserService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <message name="GetUserInfoRequest">
    <part name="userId" type="xsd:string"/>
  </message>
  <message name="GetUserInfoResponse">
    <part name="userId" type="xsd:string"/>
    <part name="username" type="xsd:string"/>
    <part name="email" type="xsd:string"/>
  </message>
  
  <portType name="UserPort">
    <operation name="GetUserInfo">
      <input message="tns:GetUserInfoRequest"/>
      <output message="tns:GetUserInfoResponse"/>
    </operation>
  </portType>

  <binding name="UserBinding" type="tns:UserPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetUserInfo">
      <soap:operation soapAction="getUserInfo"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  
  <service name="UserService">
    <port name="UserPort" binding="tns:UserBinding">
      <soap:address location="http://localhost:8001/user-service"/>
    </port>
  </service>
</definitions>
