name: CI-CD User Microservices

on:
  push:
    branches: [main, test]
    paths:
      - 'get-info-ms/**'
      - 'edit-username-ms/**'
      - 'edit-email-ms/**'
      - 'edit-avatar-ms/**'
      - 'edit-password-ms/**'
      - 'delete-account-ms/**'

  pull_request:
    branches: [main]
    paths:
      - 'get-info-ms/**'
      - 'edit-username-ms/**'
      - 'edit-email-ms/**'
      - 'edit-avatar-ms/**'
      - 'edit-password-ms/**'
      - 'delete-account-ms/**'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  #### 1. TESTS ####
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - get-info-ms
          - edit-username-ms
          - edit-email-ms
          - edit-avatar-ms
          - edit-password-ms
          - delete-account-ms
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes for service
        id: changes
        run: |
          git fetch --prune --unshallow || git fetch --all
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.base_ref }}
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep "^${{ matrix.service }}/" || true)
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^${{ matrix.service }}/" || true)
          fi
          if [[ -n "$CHANGED" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run static check (if test exists)
        if: steps.changes.outputs.changed == 'true' && hashFiles(format('{0}/tests/static_check.sh', matrix.service)) != ''
        run: bash ${{ matrix.service }}/tests/static_check.sh

  #### 2. BUILD ####
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service:
          - get-info-ms
          - edit-username-ms
          - edit-email-ms
          - edit-avatar-ms
          - edit-password-ms
          - delete-account-ms
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes for service
        id: changes
        run: |
          git fetch --prune --unshallow || git fetch --all
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.base_ref }}
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep "^${{ matrix.service }}/" || true)
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^${{ matrix.service }}/" || true)
          fi
          if [[ -n "$CHANGED" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        if: steps.changes.outputs.changed == 'true'
        run: |
          docker build -t alexismendozaa/${{ matrix.service }}:latest ./${{ matrix.service }}

      - name: Save Docker image artifact
        if: steps.changes.outputs.changed == 'true'
        run: docker save alexismendozaa/${{ matrix.service }}:latest -o ${{ matrix.service }}.tar

      - uses: actions/upload-artifact@v4
        if: steps.changes.outputs.changed == 'true'
        with:
          name: ${{ matrix.service }}-image
          path: ${{ matrix.service }}.tar

  #### 3. PUSH ####
  push:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service:
          - get-info-ms
          - edit-username-ms
          - edit-email-ms
          - edit-avatar-ms
          - edit-password-ms
          - delete-account-ms
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes for service
        id: changes
        run: |
          git fetch --prune --unshallow || git fetch --all
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            git fetch origin ${{ github.base_ref }}
            CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep "^${{ matrix.service }}/" || true)
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^${{ matrix.service }}/" || true)
          fi
          if [[ -n "$CHANGED" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/download-artifact@v4
        if: steps.changes.outputs.changed == 'true'
        with:
          name: ${{ matrix.service }}-image

      - name: Load Docker image
        if: steps.changes.outputs.changed == 'true'
        run: docker load -i ${{ matrix.service }}.tar

      - name: Login to Docker Hub
        if: steps.changes.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: steps.changes.outputs.changed == 'true'
        run: docker push alexismendozaa/${{ matrix.service }}:latest

  #### 4. DEPLOY TEST ####
  deploy_test:
    runs-on: ubuntu-latest
    needs: push
    if: github.ref == 'refs/heads/test'
    strategy:
      matrix:
        service:
          - get-info-ms
          - edit-username-ms
          - edit-email-ms
          - edit-avatar-ms
          - edit-password-ms
          - delete-account-ms
    steps:
      - uses: actions/checkout@v4
      - name: Deploy updated microservice to EC2 TEST via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_QA }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY_QA }}
          port: 22
          script: |
            docker network inspect users_network >/dev/null 2>&1 || docker network create users_network

            docker rm -f ${{ matrix.service }} || true

            docker pull alexismendozaa/${{ matrix.service }}:latest

            case "${{ matrix.service }}" in
              get-info-ms)
                docker run -d --name get-info-ms \
                  --network users_network \
                  -p 5009:3009 \
                  alexismendozaa/get-info-ms:latest
                ;;
              edit-username-ms)
                docker run -d --name edit-username-ms \
                  --network users_network \
                  -p 5004:3004 \
                  alexismendozaa/edit-username-ms:latest
                ;;
              edit-email-ms)
                docker run -d --name edit-email-ms \
                  --network users_network \
                  -p 5005:3005 \
                  alexismendozaa/edit-email-ms:latest
                ;;
              edit-avatar-ms)
                docker run -d --name edit-avatar-ms \
                  --network users_network \
                  -p 5007:3007 \
                  alexismendozaa/edit-avatar-ms:latest
                ;;
              edit-password-ms)
                docker run -d --name edit-password-ms \
                  --network users_network \
                  -p 5006:3006 \
                  alexismendozaa/edit-password-ms:latest
                ;;
              delete-account-ms)
                docker run -d --name delete-account-ms \
                  --network users_network \
                  -p 5008:3008 \
                  alexismendozaa/delete-account-ms:latest
                ;;
            esac

  #### 5. DEPLOY PROD ####
  deploy_prod:
    runs-on: ubuntu-latest
    needs: push
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service:
          - get-info-ms
          - edit-username-ms
          - edit-email-ms
          - edit-avatar-ms
          - edit-password-ms
          - delete-account-ms
    steps:
      - uses: actions/checkout@v4
      - name: Deploy updated microservice to EC2 PROD via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PROD }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY_PROD }}
          port: 22
          script: |
            docker network inspect users_network >/dev/null 2>&1 || docker network create users_network

            docker rm -f ${{ matrix.service }} || true

            docker pull alexismendozaa/${{ matrix.service }}:latest

            case "${{ matrix.service }}" in
              get-info-ms)
                docker run -d --name get-info-ms \
                  --network users_network \
                  -p 5009:3009 \
                  alexismendozaa/get-info-ms:latest
                ;;
              edit-username-ms)
                docker run -d --name edit-username-ms \
                  --network users_network \
                  -p 5004:3004 \
                  alexismendozaa/edit-username-ms:latest
                ;;
              edit-email-ms)
                docker run -d --name edit-email-ms \
                  --network users_network \
                  -p 5005:3005 \
                  alexismendozaa/edit-email-ms:latest
                ;;
              edit-avatar-ms)
                docker run -d --name edit-avatar-ms \
                  --network users_network \
                  -p 5007:3007 \
                  alexismendozaa/edit-avatar-ms:latest
                ;;
              edit-password-ms)
                docker run -d --name edit-password-ms \
                  --network users_network \
                  -p 5006:3006 \
                  alexismendozaa/edit-password-ms:latest
                ;;
              delete-account-ms)
                docker run -d --name delete-account-ms \
                  --network users_network \
                  -p 5008:3008 \
                  alexismendozaa/delete-account-ms:latest
                ;;
            esac
